language: android

android:
  components:
      - tools
      - tools
      - platform-tools
      - build-tools-24.0.1
      - android-24

      # Additional components
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-android-support

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

script:
  ./gradlew clean build check